encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("entry_edit/", views.entry_edit, name="entry_edit"),
    path("search/", views.search, name="search"),
    path("create/", views.toAdd, name="toAdd"),
    path("add/", views.add, name="add"),
    path("randomPage/", views.randomPage, name="randomPage"),
    path("<str:name>/", views.entry, name="entry"),
    path("wiki/<str:name>/", views.entry, name="entry"),
    path("<str:title>/toEdit/", views.toEdit, name="toEdit"),
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

from django.http import HttpResponse
from . import util
import random
import markdown2

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, name):
    if name not in util.list_entries():
        return HttpResponse("Requested page does not exist.")

    else:

        return render(request, "encyclopedia/entry.html", {
            "title": name,
            "entry": markdown2.markdown(util.get_entry(name)),
    })



def search(request):
    query = request.GET.get('q')
    lst = util.list_entries()

    if query in lst:

        return render(request, 'encyclopedia/entry.html', {
            "title": query,
            "entry": markdown2.markdown(util.get_entry(query)), 
        })
    else:
        subList = []
        for entry in lst:
            if query in entry:
                subList.append(entry)
        return render(request, "encyclopedia/search_sub.html", {
            "query": query,
            "subList": subList,
        })


def toAdd(request):
    return render(request, "encyclopedia/add.html", {
        "exists": False,
        "title": "",
        "entry": "",
    })


def add(request):
    title = request.POST.get('title')
    content = request.POST.get('textBody')

    lst = util.list_entries()

    if title in lst:
        return render(request, "encyclopedia/add.html", {
            "exists": True,
            "title": title,
            "entry": content

        })
    
    util.save_entry(title, content)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": markdown2.markdown(content),
    })


def randomPage(request):
    lst = util.list_entries()
    choice = random.choice(lst)

    content = util.get_entry(choice)

    return render(request, "encyclopedia/entry.html", {
        "title": choice,
        "entry": markdown2.markdown(content),
    })


def toEdit(request, title):

    content = util.get_entry(title)
    return render(request, "encyclopedia/entry_edit.html", {
        "title": title,
        "content": content,
    })


def entry_edit(request):
    title = request.POST.get('title')
    content = request.POST.get('textBody')
    util.save_entry(title, content)

    print(title)



    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": markdown2.markdown(content)
    })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add Entry
{% endblock %}

{% block body %}
    <h1>Add New Entry</h1>

    {% if exists %}
        <h2 style="color: red">Entry already exists</h2>
    {% endif %}

    <form method="post" action="{% url 'encyclopedia:add' %}">

        {% csrf_token %}


        <div>
            <input class="form-group" name="title" placeholder="Entry Title" value="{{ title }}" required>
        </div>
        <div>
            <textarea class="form-group"  name="textBody" placeholder="Content of Entry" required>{{ entry }}</textarea>
        </div>
        <button type="submit">Create entry</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}




{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <a href="toEdit">Edit page</a>
    {{ entry|safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/entry_edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit entry
{% endblock %}

{% block body %}
    <h1>Edit entry</h1>

    <form method="post" action="{% url 'encyclopedia:entry_edit' %}">

        {% csrf_token %}


        <div>
            <input class="form-group" name="title" value="{{ title }}" readonly>
        </div>
        <div>
            <textarea class="form-group"  name="textBody" required>{{ content }}</textarea>
        </div>
        <button type="submit">Save entry</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="get" action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:toAdd' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_sub.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search Results for: {{ query }}</h1>

    <ul>
        {% for entry in subList %}
            <li><a href="{% url 'encyclopedia:entry' name=entry%}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}